Asssignment1/Controllers/HomeController.cs
using Asssignment1.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Diagnostics;
//using Asssignment1.Models;

namespace Asssignment1.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            int hour = DateTime.Now.Hour;
            ViewBag.Greeting = hour < 12 ? "Good Morning" : "Good Afternoon";
            return View("Home");
        }   //  Index method
        public IActionResult LoginPage()
        {
            return View();
        }   //  LoginPage method

        public IActionResult Home()
        {
            return View();
        }   //  Home method

        public IActionResult DataPage()
        {
            return View(ReciepeList.Reciepes);
        }   //  DataPage method

        public IActionResult DisplayPage()
        {
            //Some initialized objects

            #region SaagPaneer

            #region Ingredients
            string saagPaneerIngredietsArray1 =
                "1 teaspoon turmeric\n" +
                "1/2 teaspoon cayenne\n" +
                "Kosher salt\n" +
                "3 tablespoons plus 1 1/2 tablespoons vegetable oil\n" +
                "12 ounces paneer, (Indian cheese, either store-bought or made from my recipe, recipe follows), cut into 1-inch cubes, see Cook's Note*\n" +
                "1 (16-ounce package) frozen chopped spinach\n" +
                "1 medium white onion, finely chopped\n" +
                "1 (1-inch thumb) ginger, peeled and minced (about 1 tablespoon)\n" +
                "4 cloves garlic, minced\n" +
                "1 large green serrano chile, finely chopped (seeds removed if you don't like it spicy!)\n" +
                "1/2 teaspoon store-bought or homemade garam masala, recipe follows\n" +
                "2 teaspoons ground coriander\n" +
                "1 teaspoon ground cumin\n" +
                "1/2 cup plain yogurt, stirred until smooth\n" +
                "3 large cinnamon sticks (if you have the kind you get at Indian stores, it's about 3 tablespoons of cinnamon bark bits)\n" +
                "3 tablespoons whole cloves\n" +
                "1/4 cup green cardamom pods, shelled, husks discarded (about 2 tablespoons of seeds)\n" +
                "4 large black cardamom pods, shelled, husks discarded (about 1 tablespoon of seeds), optional";
            #endregion

            #region Procedure
            string saagPaneerProcedureArray1 =
                "In a large bowl, whisk together the turmeric, cayenne, 1 teaspoon salt and 3 tablespoons oil. Gently, drop in the cubes of paneer and gently toss, taking care not to break the cubes if you're using the homemade kind. Let the cubes marinate while you get the rest of your ingredients together and prepped.\n" +
                "Thaw the spinach in the microwave in a microwave-safe dish, 5 minutes on high, then puree in a food processor until smooth. Alternatively, you can chop it up very finely with your knife\n" +
                "Place a large nonstick skillet over medium heat, and add the paneer as the pan warms. In a couple of minutes give the pan a toss; each piece of paneer should be browned on one side. Fry another minute or so, and then remove the paneer from the pan onto a plate.\n" +
                "Add the remaining 1 1/2 tablespoons oil to the pan. Add the onions, ginger, garlic and chile. Now here's the important part: saute the mixture until it's evenly toffee-coloured, which should take about 15 minutes. Don't skip this step - this is the foundation of the dish! If you feel like the mixture is drying out and burning, add a couple of tablespoons of water.\n" +
                "Add the garam masala, coriander and cumin. If you haven't already, sprinkle a little water to keep the spices from burning. Cook, stirring often, until the raw scent of the spices cook out, and it all smells a bit more melodious, 3 to 5 minutes.\n" +
                "Add the spinach and stir well, incorporating the spiced onion mixture into the spinach. Add a little salt and 1/2 cup of water, stir, and cook about 5 minutes with the lid off.\n" +
                "Turn the heat off. Add the yogurt, a little at a time to keep it from curdling. Once the yogurt is well mixed into the spinach, add the paneer. Turn the heat back on, cover and cook until everything is warmed through, about 5 minutes. Serve.\n" +
                "Combine the cinnamon sticks, cloves, green cardamom seeds, black cardamom seeds, if using into a spice grinder or coffee grinder and grind until fine. Store the spice mix in an airtight container away from direct sunlight.\n";
            #endregion

            //ViewData["saagPaneer"] = new ReciepeModel()
            //{
            //    reciepeName = "Saag Paneer",
            //    reciepeIngredients = saagPaneerIngredietsArray1,
            //    reciepeProcedure = saagPaneerProcedureArray1
            //};
            #endregion

            #region Dosa

            #region Ingredients
            string dosaIngredients =
                "3 cups rice\n" +
                "1 cup urad daal (split, skinless black gram)\n" +
                "3/4 teaspoon fenugreek seeds\n" +
                "Salt (to taste)\n" +
                "Vegetable / canola / sunflower cooking oil";
            #endregion

            #region Procedure
            string dosaProcedure =
                "Gather the ingredients.\n" +
                "Wash the rice and urad daal well. Add the fenugreek seeds to the mix and fill enough water in the rice-daal bowl to cover them about 2-inch deep. Soak overnight.\n" +
                "The next morning, drain all the water from the rice and urad daal. Now put some in a food processor and grind - adding very little water if necessary - to a smooth yet slightly grainy paste.\n" +
                "When all the rice-daal mix is ground like this, put it into a large mixing bowl and add enough water to make a batter. The consistency of the batter should be such that it thickly coats a spoon dipped in it.\n" +
                "Now add salt to taste and keep the Dosa batter aside in a warm, dark spot, covered, for 6 to 8 hours. After this fermentation, stir the batter well. It is now ready to make Dosas.\n" +
                "Put some cooking oil in a small bowl and keep ready. You will also need a bowl of ice cold water, a large, flat nonstick pan, 2 sheets of paper towel, a ladle, a spatula and a basting brush.\n" +
                "Fold one sheet of paper towel into a wad and dip lightly into the bowl of cooking oil. Squeeze out any excess and then rub the paper towel all over the surface of the pan to grease. The correct amount of oil is such that it is barely visible in the pan. Now turn on the heat/ flame at medium high.\n" +
                "Fill the ladle up to the 3/4 level with Dosa batter. Gently pour this batter onto the center of the pan - just as you would for a pancake - till the ladle is empty.\n" +
                "Now begin to spread the batter in sweeping circular motions to form a pancake of roughly 8-inch diameter. Do not be alarmed if the Dosa develops tiny holes as you spread the batter. This is normal.\n" +
                "As soon as you have finished spreading the batter out on the pan, dip the basting brush in cooking oil and drizzle the oil all over the surface of the dosa and also around its edges. Now hold the pan by its handle, lift up and swirl it so as to make the drizzled oil spread all over the Dosa.​\n" +
                "When the upper surface begins to look cooked (it will no longer look soft or runny), flip the Dosa. By this time, ideally, the surface that was underneath should be light golden in color. Cook for 1 minute after flipping.\n" +
                "The Dosa is almost done. Fold it in half and allow to cook for 30 seconds more.\n" +
                "Before you start making the next Dosa, fold another sheet of paper towel into a wad and dip it in ice cold water. Squeeze the wad to remove excess water and then rub it all over the surface of the pan to cool it slightly. This ensures your next Dosa will spread evenly and not break because the pan is too hot. Now proceed as you did for the last Dosa.\n" +
                "We like to make and serve Dosas immediately while we cook as this means they are crisp and fresh when eaten. This, however, is not absolutely necessary. You can also make, stack and serve the Dosas later. Just ensure you keep them warm until serving time by placing them - just like with pancakes - in a closed dish.\n" +
                "Serve the ready Dosa with side dishes like South Indian coconut chutney, South Indian gunpowder chutney, and sambar.";
            #endregion

            //ViewData["Dosa"] = new ReciepeModel()
            //{
            //    reciepeName = "Dosa",
            //    reciepeIngredients = dosaIngredients,
            //    reciepeProcedure = dosaProcedure
            //};
            #endregion

            ReciepeModel reciepe1 = new ReciepeModel
            {
                reciepeName = "Saag Paneer",
                reciepeIngredients = saagPaneerIngredietsArray1,
                reciepeProcedure = saagPaneerProcedureArray1
            };

            ReciepeModel reciepe2 = new ReciepeModel
            {
                reciepeName = "Dosa",
                reciepeIngredients = dosaIngredients,
                reciepeProcedure = dosaProcedure
            };

            //ReciepeList.AddReciepe(reciepe1);
            //ReciepeList.AddReciepe(reciepe2);

            return View(ReciepeList.Reciepes);
        }   //  DisplayPage method

        public IActionResult InsertPage()
        {
            return View();
        }   //  InsertPage method

        [HttpGet]
        public ViewResult _ReciepeResult()
        {
            return View("InsertPage");
        }

        [HttpPost]
        public ViewResult _ReciepeResult(ReciepeModel reciepe)

Asssignment1/Controllers/ReciepeModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Asssignment1.Models;

namespace Asssignment1.Controllers
{
    public class ReciepeModelsController : Controller
    {
        private readonly ReciepesAllContext _context;

        public ReciepeModelsController(ReciepesAllContext context)
        {
            _context = context;
        }

        // GET: ReciepeModels
        public async Task<IActionResult> Index()
        {
            return View(await _context.ReciepeModel.ToListAsync());
        }

        // GET: ReciepeModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reciepeModel = await _context.ReciepeModel
                .SingleOrDefaultAsync(m => m.Id == id);
            if (reciepeModel == null)
            {
                return NotFound();
            }

            return View(reciepeModel);
        }

        // GET: ReciepeModels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ReciepeModels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,reciepeName,reciepeIngredients,reciepeProcedure")] ReciepeModel reciepeModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(reciepeModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(reciepeModel);
        }

        // GET: ReciepeModels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reciepeModel = await _context.ReciepeModel.SingleOrDefaultAsync(m => m.Id == id);
            if (reciepeModel == null)
            {
                return NotFound();
            }
            return View(reciepeModel);
        }

        // POST: ReciepeModels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,reciepeName,reciepeIngredients,reciepeProcedure")] ReciepeModel reciepeModel)
        {
            if (id != reciepeModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(reciepeModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReciepeModelExists(reciepeModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(reciepeModel);
        }

        // GET: ReciepeModels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reciepeModel = await _context.ReciepeModel
                .SingleOrDefaultAsync(m => m.Id == id);
            if (reciepeModel == null)
            {
                return NotFound();
            }

            return View(reciepeModel);
        }

        // POST: ReciepeModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var reciepeModel = await _context.ReciepeModel.SingleOrDefaultAsync(m => m.Id == id);
            _context.ReciepeModel.Remove(reciepeModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReciepeModelExists(int id)
        {
            return _context.ReciepeModel.Any(e => e.Id == id);
        }
    }
}

Asssignment1/Views/Home/DataPage.cshtml
@model List<Asssignment1.Models.ReciepeModel>

@{
    Layout = "_Layout";
    ViewBag.Title = "DataPage";
}

@{
    var reciepe = ViewData["reciepe"] as Asssignment1.Models.ReciepeList;
}

<body>
    <!--Jumbotron-->
    <div class="jumbotrons">

        <div class="jumbotrons">
            <div class="jumbotron jumbotron-fluid">
                <div class="center-block">
                    <div class="card text-center">
                        <div class="card-body">
                            <h2>Data Page</h2>
                            <h3>List of Reciepes.</h3>
                        </div>
                    </div>
                </div>
            </div>

            <!--saagPaneer-->
            <div class="jumbotron jumbotron-fluid">

                <!--Constant array values-->
                <!--Just here for future reference-->
                @*<div class="center-block">
                        <div class="card text-center">

                            @for (int i = 0; i < reciepe.reciepeList.Length; i++)
                            {

                                <div class="card-body">
                                    <reciepes>
                                        <ul class="list-group list-group-flush">
                                            <li class="list-group-item-action">
                                                @if (i % 2 == 0)
                                                {
                                                    <h2 class="active">
                                                        @reciepe.reciepeList[i]
                                                    </h2>
                                                }
                                                @if (i % 2 != 0)
                                                {
                                                    <h2 class="alert-dark">
                                                        @reciepe.reciepeList[i]
                                                    </h2>
                                                }
                                            </li>
                                        </ul>
                                    </reciepes>
                                </div>
                            }
                        </div>
                    </div>*@

                <!--Jombotron end-->
                <!--To be included after the display page is made-->
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Reciepe Name</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            int i = 1;
                            foreach (var a in Model)
                            {
                                <tr>
                                    <td>Reciepe #@i</td>
                                    <th scope="row">@a.reciepeName</th>

                                    <!--Displaying only name in data page-->
                                    @*<td>@a.reciepeIngredients</td>
                                        <td>@a.reciepeProcedure</td>*@
                                </tr>
                                i++;
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>

</body>

Asssignment1/Views/Home/DisplayPage.cshtml
@model List<Asssignment1.Models.ReciepeModel>

@{
    Layout = "_Layout";
    ViewBag.Title = "DisplayPage";
}
@*@{
        var saagPaneer = ViewData["saagPaneer"] as Asssignment1.Models.ReciepeModel;
        var dosa = ViewData["dosa"] as Asssignment1.Models.ReciepeModel;
    }*@
<body>
    <!--Jumbotron-->
    <div class="jumbotrons">
        <div class="jumbotron jumbotron-fluid">
            <div class="center-block">
                <div class="card text-center">
                    <div class="card-body">
                        <h2>Dispay Page</h2>
                        <h3>Reciepes are displayed here.</h3>
                    </div>
                </div>
            </div>
        </div>

        <!--Rendering model data from partial view.-->
        @*@{ Html.RenderPartial("_ReciepeResult"); }*@

        <!--1st reciepe-->
        <div class="jumbotrons">
            <div class="jumbotron jumbotron-fluid">

                <!--Data from stored values-->
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Reciepe Name</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            int i = 1;
                            foreach (var a in Model)
                            {
                                <tr>
                                    <td>Reciepe #@i</td>
                                    <th scope="row">@a.reciepeName</th>
                                    <!--Displaying only name in data page-->
                                    <td>@a.reciepeIngredients</td>
                                    <td>@a.reciepeProcedure</td>
                                </tr>
                                i++;
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>

        <!--Jombotron end-->
</body>

Asssignment1/Views/Home/Home.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewBag.Title = "Home";
    Layout = null;
}

<!Doctype html>
<html>
<div class="alignment">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>HomePage</title>

        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.min.css" />
        <link rel="stylesheet" href="~/css/custom.css" />
        <link rel="stylesheet" href="~/lib/bootstrap-4.0.0/bootstrap-4.0.0/dist/css/bootstrap.min.css" />

        <!--Bootstrap javascript links-->

        <!--Should be removed if layout is added-->
        <!--Navbar-->
        <nav class="nav nav-tabs">
            <div class="container">
                <div class="navbar-header">
                    <div class="float-lg-right">
                        <button class="nav-item"><a asp-controller="Home" asp-action="LoginPage">Login</a></button>
                    </div>
                </div>
                <div class="navbar-collapse">
                    <ul class="nav navbar-nav navbar-right"></ul>
                </div>
            </div>
        </nav>
        <!--Navbar Ending-->
        <!--Should be removed if layout is added-->

    </head>

    <body>

        <!--Jumbotron-->
        <div class="jumbotrons">
            <div class="jumbotron jumbotron-fluid">
                <div class="center-block">
                    <div class="card text-center">
                        <div class="card-body">
                            <h2>Login to your Portal</h2>
                            <h3>@ViewBag.Greeting Chefs</h3>
                        </div>
                    </div>
                </div>
            </div>

            <!--Corousal-->
            <div class="jumbotron" id="corousel">
                <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img class="d-block w-100" src="~/images/Home_image1.jpg" alt="First slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block w-100" src="~/images/Home_image2.jpg" alt="Second slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block w-100" src="~/images/Home_image3.jpg" alt="Third slide">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
        </div>
        <!--Corousal End-->
        <!--Jombotron end-->
        <!-- Footer -->
        <footer class="page-footer font-small blue">

            <!-- Copyright -->
            <div class="footer-copyright text-center py-3">
                © 2018 Copyright:
                <a href="https://portfolioharkiratgrewal.herokuapp.com/"> Harkirat Singh Grewal</a>
            </div>
            <!-- Copyright -->

        </footer>
        <!-- Footer -->
        <!--Bootstrap Javascripts-->
        <script src="~/lib/Popper.js/popper.min.js"></script>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap-4.0.0/bootstrap-4.0.0/js/dist/carousel.js"></script>
        <script src="~/lib/bootstrap-4.0.0/bootstrap-4.0.0/js/dist/util.js"></script>

    </body>
</div>
</html>
</html>

Asssignment1/Views/Home/InsertPage.cshtml
@model Asssignment1.Models.ReciepeModel

@{
    Layout = "_Layout";
    ViewBag.Title = "InsertPage";
}
<body>
    <!--Jumbotron-->
    <div class="jumbotrons">
        <div class="jumbotron jumbotron-fluid">
            <div class="center-block">
                <div class="card text-center">
                    <div class="card-body">
                        <h2>Insert Page</h2>
                        <h3>Enter your special ingredient reciepe here to store as cache.</h3>
                        <h3>Click below for <b>Database</b></h3>
                        <h6>For full marks</h6>
                        <h6>||</h6>
                        <h6>V</h6>
                        <a asp-controller="ReciepeModels" asp-action="Index"><input type ="submit" value="Database" class ="btn btn-primary"/></a>
                    </div>
                </div>
            </div>
        </div>

        <div class="jumbotron">
            <div class="card text-center">
                <div class="card-body">
                    <!--Partial rendering form-->
                    @Html.Partial("_ReciepeResult")
                </div>
            </div>
        </div>

    </div>
    <!--Jombotron end-->
</body>

Asssignment1/Views/Home/LoginPage.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = null;
}

<!Doctype html>
<html>
<div class="alignment">
    <head>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.min.css" />
        <link rel="stylesheet" href="~/css/custom.css" />
        <link rel="stylesheet" href="~/lib/bootstrap-4.0.0/bootstrap-4.0.0/dist/css/bootstrap.min.css" />
        <script src="~/lib/bootstrap-4.0.0/bootstrap-4.0.0/dist/js/bootstrap.min.js"></script>

        <!--Navbar-->
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" asp-controller="Home" asp-action="LoginPage">Login</a>
            </li>
            <li>
                <a class="nav-link" asp-controller="Home" asp-action="Home">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Logging In...</a>
            </li>
        </ul>
        <!--Navbar Ending-->

    </head>
    <body>
        <!--Jumbotron-->
        <div class="jumbotrons">
            <div class="jumbotron jumbotron-fluid">
                <div class="center-block">
                    <div class="card text-center">
                        <div class="card-body">
                            <h2>Login to your Portal</h2>
                            <h3>Welcome @ViewBag.Username</h3>
                        </div>
                    </div>
                </div>
            </div>

            <div class="jumbotron">
                <form>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Email address</label>
                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
                        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Password</label>
                        <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
                    </div>
                    <div class="form-check">
                        <input type="checkbox" class="form-check-input" id="exampleCheck1">
                        <label class="form-check-label" for="exampleCheck1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Check me out</label>
                    </div>
                    <a asp-controller="Home" asp-action="UserPage"><button type="button" class="btn btn-primary">Submit</button></a>
                </form>
            </div>
        </div>
        <!--Jombotron end-->
        <!-- Footer -->
        <footer class="page-footer font-small blue">

            <!-- Copyright -->
            <div class="footer-copyright text-center py-3">
                © 2018 Copyright:
                <a href="https://portfolioharkiratgrewal.herokuapp.com/"> Harkirat Singh Grewal</a>
            </div>
            <!-- Copyright -->

        </footer>
        <!-- Footer -->
    </body>
</div>
</html>

Asssignment1/Views/Home/UserPage.cshtml
@*
    //Adding models here
*@

@{
    Layout = "_Layout";
    ViewBag.Title = "UserPage";
}
<body>
    <!--Jumbotron-->
    <div class="jumbotrons">
        <div class="jumbotron jumbotron-fluid">
            <div class="center-block">
                <div class="card text-center">
                    <div class="card-body">
                        <h2>User Page</h2>
                        <h3>Details for the user goes here.</h3>
                        <h3>Note: The database functionality is added under the InsertPage and clicking on <b>Database</b> button.</h3>
                    </div>
                </div>
            </div>
        </div>

        <div class="jumbotron">
            <div class="card" style="width: 940px;">
                <nav class="navbar navbar-dark bg-dark">
                    <h2 class="bg-info">Profile</h2>
                </nav>
                <div class="card-body">
                    <h1 class="card-title">@ViewBag.userName</h1>
                    <p class="card-text">Welcome chef, this is your profile. Editing would be added soon.</p>
                    <a href="#" class="btn btn-primary">Edit</a>    
                </div>
            </div>
        </div>
    </div>
    <!--Jombotron end-->
</body>